### ISSUE TITLE
Error witch VueJS 2.0

### ISSUE THREAD

**Issue by xereda** [vue-bulma/switch#1]
Hello,

Please, review this error:

titulo do site

``` 
ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-20f464ff!./~/vue-loader/lib/selector.js?type=template&index=0!./~/vue-bulma-switch/src/Switch.vue
Module parse failed: /Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/vue-loader/lib/template-compiler.js?id=data-v-20f464ff!/Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/vue-loader/lib/selector.js?type=template&index=0!/Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/vue-bulma-switch/src/Switch.vue 'with' in strict mode (1:35)
You may need an appropriate loader to handle this file type.
SyntaxError: 'with' in strict mode (1:35)
    at Parser.pp$4.raise (/Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$1.parseWithStatement (/Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/acorn/dist/acorn.js:932:27)
    at Parser.pp$1.parseStatement (/Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/acorn/dist/acorn.js:708:32)
    at Parser.pp$1.parseBlock (/Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (/Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/acorn/dist/acorn.js:2105:24)
    at Parser.pp$1.parseFunction (/Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/acorn/dist/acorn.js:1065:10)
    at Parser.pp$3.parseExprAtom (/Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/acorn/dist/acorn.js:1810:19)
    at Parser.pp$3.parseExprSubscripts (/Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parsePropertyValue (/Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/acorn/dist/acorn.js:1998:89)
    at Parser.pp$3.parseObj (/Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/acorn/dist/acorn.js:1989:14)
    at Parser.pp$3.parseExprAtom (/Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/acorn/dist/acorn.js:1805:19)
    at Parser.pp$3.parseExprSubscripts (/Users/xereda/Sites/docmob.local/docmob.portal.vuejs2.0/node_modules/acorn/dist/acorn.js:1715:21)
 @ ./~/vue-bulma-switch/src/Switch.vue 10:23-146

```

Tks

Jackson

**Comment by mattattui** [comment]
This is fixed in master (alternatively you can change line 2 of `Switch.vue` to:

```html
  <label class="switch" :class="{ [`is-${type}`]: type, [`is-${size}`]: size, ['checked']: value }">
```

@fundon - would be great if you could tag another release so we can use this!

**Comment by xereda** [comment]
Is this already up to date?

**Comment by xereda** [comment]
I can imagine how much it is working! I see that your effort will bring excellent results in the future.

With regard to "tabs" being absolutely at the bottom, within a component, there is no way to do. It is!?

Thank you for your help.

**Comment by fundon** [comment]
@xereda @inanimatt Thank  you!

It still exists in latest version?

**Comment by moonlik** [comment]
Same problem. NPM version is outdated. @fundon please, update it.

**Comment by fundon** [comment]
@moonlik @xereda @inanimatt Try https://github.com/vue-bulma/switch/releases/tag/v1.0.1. Thanks.
